#!/usr/bin/env python3
"""
Language dictionary and translation function
"""

from utils.color import Color

LANG = {
    # General
    "invalid_option": "Invalid option, please try again.",
    "press_enter": "Press Enter to continue...",
    "yes": "yes",
    "no": "no",
    "input_required": "This field cannot be empty.",
    "success": "✅ Success",
    "fail": "❌ Failed",
    "sep_line": "-" * 40,
    "main_menu_title": f"{Color.BOLD}{Color.CYAN}Kubernetes Resource Manager {{version}}{Color.END}",
    "main_menu_1": "1. POD",
    "main_menu_2": "2. SERVICE",
    "main_menu_3": "3. INGRESS",
    "main_menu_4": "4. DEPLOYMENT",
    "main_menu_5": "5. DAEMONSET",
    "main_menu_6": "6. K8S CLUSTER MAINTENANCE",
    "main_menu_7": "7. K8S MANAGER SYSTEM TOOLS",
    "main_menu_8": "8. Exit",
    "main_menu_prompt": "Select resource type (1-8): ",
    "goodbye": "Goodbye!",
    "kubectl_check_fail": "Error: kubectl not found or not available. Please ensure kubectl is installed and kubeconfig is configured.",
    "version_init": "Initialized version log, current version: {version}",
    "version_upgrade_record": "Detected version upgrade: {old} -> {new}, recorded.",
    "version_history_title": f"{Color.CYAN}--- Version Update History ---{Color.END}",
    "version_no_history": "No version history available.",

    # Pod submenu
    "pod_menu_title": f"{Color.CYAN}--- Pod Management ---{Color.END}",
    "pod_menu_1": "1. Create Pod",
    "pod_menu_2": "2. Delete Pod",
    "pod_menu_3": "3. List all Pods",
    "pod_menu_4": "4. Describe Pod",
    "pod_menu_5": "5. Back to Main Menu",
    "pod_menu_prompt": "Choose (1-5): ",
    
    # Create Pod submenu
    "create_pod_submenu_title": f"{Color.CYAN}--- Create Pod Options ---{Color.END}",
    "create_pod_submenu_1": "1. Quick Deploy (Interactive Wizard)",
    "create_pod_submenu_2": "2. Create YAML (Edit YAML file manually)",
    "create_pod_submenu_3": "3. Back to Pod Management",
    "create_pod_submenu_prompt": "Choose (1-3): ",
    
    # Quick Deploy (Pod)
    "create_pod_title": f"{Color.CYAN}--- Create Pod (Quick Deploy) ---{Color.END}",
    "create_pod_name": "Pod name",
    "create_pod_image": "Image (e.g., nginx:latest)",
    "create_pod_port": "Container port",
    "create_pod_env_ask": "Add environment variables?",
    "create_pod_env_key": "  Environment variable name",
    "create_pod_env_value": "  Environment variable value",
    
    # Pod YAML Editor
    "yaml_editor_title": f"{Color.CYAN}--- Create Pod (YAML Editor) ---{Color.END}",
    "yaml_file_created": "YAML template created: {file}",
    "yaml_editor_check": "Checking for vim editor...",
    "yaml_editor_not_found": "❌ vim editor not found on this system.",
    "yaml_editor_install_prompt": "Do you want to install vim?",
    "yaml_editor_installing": "Installing vim...",
    "yaml_editor_install_success": "✅ vim installed successfully.",
    "yaml_editor_install_failed": "❌ Failed to install vim. Please install manually and try again.",
    "yaml_editor_open": "Opening vim to edit {file}...",
    "yaml_editor_edit_hint": "Edit the YAML file, then save and exit (:wq).",
    "yaml_editor_press_enter": "Press Enter to open vim...",
    "yaml_editor_backup": "Backup created: {backup}",
    "yaml_validate": "Validating YAML syntax...",
    "yaml_validate_success": "✅ YAML syntax validation passed.",
    "yaml_validate_fail": "❌ YAML syntax error at line {line}: {error}",
    "yaml_validate_retry": "Do you want to edit again?",
    "kubectl_validate": "Validating with kubectl...",
    "kubectl_validate_success": "✅ kubectl validation passed.",
    "kubectl_validate_fail": "❌ kubectl validation failed:\n{error}",
    "apply_pod": "Creating Pod...",
    "apply_success": "✅ Pod '{name}' created successfully!",
    "apply_fail": "❌ Failed to create Pod: {error}",
    "yaml_file_saved": "YAML file saved at: {file}",
    "yaml_editor_aborted": "Pod creation cancelled.",
    
    # Delete Pod
    "delete_pod_title": f"{Color.CYAN}--- Delete Pod ---{Color.END}",
    "delete_pod_name": "Pod name or number to delete",
    "delete_pod_hint": "Enter numbers separated by space (e.g., '1 3 5'), 'q' to quit, 'menu' to return, or Pod name",
    "delete_pod_invalid": "Invalid number or Pod name, please try again.",
    "delete_pod_not_found": "Pod with number {num} not found, please try again.",
    "delete_pod_confirm_single": "Confirm deletion of Pod '{name}'?",
    "delete_pod_confirm_multiple": "Confirm deletion of {count} Pods?",
    "delete_pod_success": "✅ Pod '{name}' deleted successfully.",
    "delete_pod_fail": "❌ Failed to delete pod '{name}': {error}",
    "delete_pod_no_pods": "No Pods available to delete.",
    "delete_pod_summary": "Deletion Summary:",
    "delete_more_prompt": "Do you want to delete more Pods?",
    "delete_try_again": "Do you want to try deleting different Pods?",
    "delete_exiting": "Exiting delete mode...",
    "delete_returning": "Returning to Pod Management menu...",
    "delete_no_input": "No input provided. Returning to menu...",
    "delete_no_valid": "No valid Pods selected for deletion.",
    "delete_cancelled": "Deletion cancelled.",
    
    # List Pods
    "list_pods_title": f"{Color.CYAN}--- Current Pod List ---{Color.END}",
    "list_pods_fail": "Failed to list Pods",
    "list_pods_no_pods": "No running Pods in current namespace.",
    
    # Describe Pod
    "describe_pod_title": f"{Color.CYAN}--- Describe Pod ---{Color.END}",
    "describe_pod_name": "Pod name or number to describe",
    "describe_pod_hint": "Enter number (e.g., 1) or Pod name (e.g., nginx-pod)",
    "describe_pod_fetch": "Fetching details for Pod '{name}'...",
    "describe_pod_fail": "Failed to describe Pod",
    
    # Deployment submenu (updated with Edit)
    "deployment_menu_title": f"{Color.CYAN}--- Deployment Management ---{Color.END}",
    "deployment_menu_1": "1. Create Deployment",
    "deployment_menu_2": "2. Delete Deployment",
    "deployment_menu_3": "3. List all Deployments",
    "deployment_menu_4": "4. Describe Deployment",
    "deployment_menu_5": "5. Export Deployment to YAML",
    "deployment_menu_6": "6. Edit Deployment",
    "deployment_menu_7": "7. Back to Main Menu",
    "deployment_menu_prompt": "Choose (1-7): ",
    
    # Export Deployment submenu
    "export_deployment_menu_title": f"{Color.CYAN}--- Export Deployment to YAML ---{Color.END}",
    "export_deployment_1": "1. Display YAML to screen",
    "export_deployment_2": "2. Save YAML to file",
    "export_deployment_3": "3. Back to Deployment Management",
    "export_deployment_prompt": "Choose (1-3): ",
    "export_select_deployment": "Select Deployment (number or name): ",
    "export_fetching": "Fetching YAML for Deployment '{name}'...",
    "export_display_title": f"{Color.CYAN}--- YAML of Deployment '{{name}}' ---{Color.END}",
    "export_save_success": "✅ Deployment YAML saved to: {file}",
    "export_save_overwrite": f"{Color.YELLOW}File '{{file}}' already exists. Overwrite?{Color.END}",
    "export_save_cancelled": "Save cancelled.",
    "export_fail": "❌ Failed to export Deployment: {error}",
    "export_not_found": "Deployment not found: {name}",
    
    # Edit Deployment submenu
    "edit_deployment_menu_title": f"{Color.CYAN}--- Edit Deployment ---{Color.END}",
    "edit_deployment_menu_1": "1. Direct Edit (kubectl edit)",
    "edit_deployment_menu_2": "2. Edit via YAML file",
    "edit_deployment_menu_3": "3. Back to Deployment Management",
    "edit_deployment_menu_prompt": "Choose (1-3): ",
    
    # Direct edit
    "edit_deployment_direct_title": f"{Color.CYAN}--- Direct Edit ---{Color.END}",
    "edit_deployment_direct_start": "Opening editor for Deployment '{name}'...",
    "edit_deployment_direct_success": "✅ Deployment updated successfully.",
    "edit_deployment_direct_fail": "❌ Failed to update Deployment. See errors above.",
    
    # YAML file edit
    "edit_deployment_yaml_title": f"{Color.CYAN}--- Edit via YAML File ---{Color.END}",
    "edit_deployment_yaml_path_prompt": "Enter absolute path to YAML file: ",
    "edit_deployment_yaml_path_empty": "❌ Path cannot be empty.",
    "edit_deployment_yaml_not_found": "❌ File not found: {path}",
    "edit_deployment_yaml_edit_before": "Do you want to edit the YAML file before applying?",
    "edit_deployment_yaml_open_editor": "Opening editor...",
    "edit_deployment_yaml_applying": "Applying YAML file...",
    "edit_deployment_yaml_success": "✅ Deployment updated successfully.",
    "edit_deployment_yaml_fail": "❌ Failed to update Deployment.",
    
    # Create Deployment submenu
    "create_deployment_submenu_title": f"{Color.CYAN}--- Create Deployment Options ---{Color.END}",
    "create_deployment_submenu_1": "1. Quick Deploy (Interactive Wizard)",
    "create_deployment_submenu_2": "2. Create YAML (Edit YAML file manually)",
    "create_deployment_submenu_3": "3. Back to Deployment Management",
    "create_deployment_submenu_prompt": "Choose (1-3): ",
    
    # Quick Deploy (Deployment)
    "create_deployment_title": f"{Color.CYAN}--- Create Deployment (Quick Deploy) ---{Color.END}",
    "create_deployment_name": "Deployment name",
    "create_deployment_image": "Image (e.g., nginx:latest)",
    "create_deployment_replicas": "Number of replicas",
    "create_deployment_port": "Container port",
    "create_deployment_env_ask": "Add environment variables?",
    "create_deployment_env_key": "  Environment variable name",
    "create_deployment_env_value": "  Environment variable value",
    
    # Deployment YAML Editor
    "deployment_yaml_editor_title": f"{Color.CYAN}--- Create Deployment (YAML Editor) ---{Color.END}",
    "deployment_yaml_file_created": "YAML template created: {file}",
    "deployment_yaml_editor_aborted": "Deployment creation cancelled.",
    "deployment_apply_success": "✅ Deployment '{name}' created successfully!",
    
    # Delete Deployment
    "delete_deployment_title": f"{Color.CYAN}--- Delete Deployment ---{Color.END}",
    "delete_deployment_name": "Deployment name or number to delete",
    "delete_deployment_hint": "Enter numbers separated by space (e.g., '1 3 5'), 'q' to quit, 'menu' to return, or Deployment name",
    "delete_deployment_invalid": "Invalid number or Deployment name, please try again.",
    "delete_deployment_not_found": "Deployment with number {num} not found, please try again.",
    "delete_deployment_confirm_single": "Confirm deletion of Deployment '{name}'?",
    "delete_deployment_confirm_multiple": "Confirm deletion of {count} Deployments?",
    "delete_deployment_success": "✅ Deployment '{name}' deleted successfully.",
    "delete_deployment_fail": "❌ Failed to delete deployment '{name}': {error}",
    "delete_deployment_no_pods": "No Deployments available to delete.",
    "delete_deployment_summary": "Deletion Summary:",
    
    # List Deployments
    "list_deployments_title": f"{Color.CYAN}--- Current Deployment List ---{Color.END}",
    "list_deployments_fail": "Failed to list Deployments",
    "list_deployments_no_deployments": "No Deployments in current namespace.",
    
    # Describe Deployment
    "describe_deployment_title": f"{Color.CYAN}--- Describe Deployment ---{Color.END}",
    "describe_deployment_name": "Deployment name or number to describe",
    "describe_deployment_hint": "Enter number (e.g., 1) or Deployment name",
    "describe_deployment_fetch": "Fetching details for Deployment '{name}'...",
    "describe_deployment_fail": "Failed to describe Deployment",
    
    # Other resource placeholders
    "service_menu_title": f"{Color.CYAN}--- Service Management ---{Color.END}",
    "service_menu_dev": "Feature in development, coming soon.",
    "ingress_menu_title": f"{Color.CYAN}--- Ingress Management ---{Color.END}",
    "daemonset_menu_title": f"{Color.CYAN}--- DaemonSet Management ---{Color.END}",
    
    # Cluster Maintenance submenu
    "cluster_menu_title": f"{Color.CYAN}--- K8S Cluster Maintenance ---{Color.END}",
    "cluster_menu_1": "1. Show cluster details",
    "cluster_menu_2": "2. Show all nodes details",
    "cluster_menu_3": "3. Show version update history",
    "cluster_menu_4": "4. Back to Main Menu",
    "cluster_menu_prompt": "Choose (1-4): ",
    "cluster_info_title": f"{Color.CYAN}--- Cluster Details ---{Color.END}",
    "nodes_info_title": f"{Color.CYAN}--- All Node Details ---{Color.END}",
    "nodes_info_fail": "Failed to get node information",
    
    # System Tools menu
    "tools_menu_title": f"{Color.CYAN}--- K8S Manager System Tools ---{Color.END}",
    "tools_menu_1": "1. Program Upgrade",
    "tools_menu_2": "2. YAML File Management",
    "tools_menu_3": "3. Upload to GitHub (Git CLI)",
    "tools_menu_4": "4. Back to Main Menu",
    "tools_menu_prompt": "Choose (1-4): ",
    
    # GitHub Upload (Git CLI)
    "git_upload_title": f"{Color.CYAN}--- Upload to GitHub (Git CLI) ---{Color.END}",
    "git_check_install": "Checking Git installation...",
    "git_not_installed": "❌ Git is not installed on this system.",
    "git_install_prompt": "Do you want to install Git? (requires sudo)",
    "git_installing": "Installing Git...",
    "git_install_success": "✅ Git installed successfully.",
    "git_install_failed": "❌ Failed to install Git. Please install manually and try again.",
    "git_check_repo": "Checking if current directory is a Git repository...",
    "git_init": "Initializing Git repository...",
    "git_init_success": "✅ Git repository initialized.",
    "git_remote_check": "Checking remote origin...",
    "git_remote_prompt": "Enter GitHub repository URL (e.g., https://github.com/username/repo.git or git@github.com:username/repo.git): ",
    "git_remote_add": "Adding remote origin...",
    "git_remote_success": "✅ Remote origin configured.",
    "git_add_file": "Adding script to Git...",
    "git_add_success": "✅ File added to Git.",
    "git_commit": "Committing changes...",
    "git_commit_message": "Enter commit message [default: Upload {filename}]: ",
    "git_commit_success": "✅ Changes committed.",
    "git_push": "Pushing to GitHub...",
    "git_push_success": "✅ Successfully pushed to GitHub!",
    "git_push_fail": "❌ Push failed: {error}",
    "git_no_changes": "No changes to commit. Checking if file is already tracked and up-to-date.",
    "git_up_to_date": "✅ File is already up-to-date on GitHub.",
    "git_identity_check": "Checking Git user identity...",
    "git_identity_missing": "Git user name or email not configured.",
    "git_identity_name_prompt": "Enter your name: ",
    "git_identity_email_prompt": "Enter your email: ",
    "git_identity_success": "✅ Git user identity configured locally.",
    
    # YAML File Management
    "yaml_management_title": f"{Color.CYAN}--- YAML File Management ---{Color.END}",
    "yaml_list_title": "Available YAML files:",
    "yaml_no_files": "No YAML files found in current directory.",
    "yaml_select_prompt": "Enter numbers separated by space (e.g., '1 3 5'), 'q' to quit, 'menu' to return",
    "yaml_delete_confirm_single": "Confirm deletion of YAML file '{name}'?",
    "yaml_delete_confirm_multiple": "Confirm deletion of {count} YAML files?",
    "yaml_delete_success": "✅ YAML file '{name}' deleted successfully.",
    "yaml_delete_fail": "❌ Failed to delete YAML file '{name}': {error}",
    "yaml_delete_summary": "Deletion Summary:",
    "yaml_invalid": "Invalid selection, please try again.",
    "yaml_not_found": "File with number {num} not found.",
    "yaml_view": "View YAML file content",
    "yaml_view_prompt": "Enter number to view file content (or 'q' to quit): ",
    "yaml_view_title": f"{Color.CYAN}--- YAML File Content ---{Color.END}",
    
    # Program Upgrade
    "upgrade_title": f"{Color.CYAN}--- Program Upgrade (Custom File) ---{Color.END}",
    "upgrade_step1": "Step 1: Enter the full path of the new script (must be a .py file)",
    "upgrade_step1_prompt": "Path: ",
    "upgrade_step1_empty": "❌ Path cannot be empty.",
    "upgrade_step1_abs": "Absolute path entered: {path}",
    "upgrade_step2": "Step 2: Validating file...",
    "upgrade_step2_notexist": "❌ File does not exist. Please check the path.",
    "upgrade_step2_ext": "❌ File extension is not .py. Please select a Python script.",
    "upgrade_step2_same": "❌ The new file is the same as the current script. Upgrade aborted.",
    "upgrade_step2_pass": "✅ File validation passed.",
    "upgrade_step3": "Step 3: Checking write permission on script directory...",
    "upgrade_step3_fail": "❌ You do not have write permission on the script directory.",
    "upgrade_step3_fail_suggestion": "Please run as administrator or modify directory permissions.",
    "upgrade_step3_pass": "✅ Permission check passed. Ready to proceed.",
    "upgrade_step4": "Step 4: Backing up current script...",
    "upgrade_step4_backup": "✅ Backup created: {backup}",
    "upgrade_step4_fail": "❌ Backup failed: {error}",
    "upgrade_step5": "Step 5: Replacing current script with new version...",
    "upgrade_step5_success": "✅ Upgrade successful! New version is now active.",
    "upgrade_step5_fail": "❌ Replacement failed: {error}",
    "upgrade_step5_restore": "Original file restored.",
    "upgrade_step5_restore_fail": "Restore also failed: {error}. Please handle manually.",
    "upgrade_step6": "Step 6: Verifying new script readability and executability...",
    "upgrade_cleanup": "Step 7: Cleaning up backup file...",
    "upgrade_step6_fail_noread": "❌ New script is not readable. Restoring original file.",
    "upgrade_step6_fail_noexec": "⚠️ New script lacks execute permission, attempting to add execute permission...",
    "upgrade_step6_fail_noexec_sudo": "Failed to add permission normally, trying with sudo...",
    "upgrade_step6_success": "✅ File permission check passed.",
    "upgrade_cleanup_deleted": "✅ Backup file deleted.",
    "upgrade_restart": "Restarting new program automatically...",
    "upgrade_restart_fail": "❌ Restart failed: {error}",
    "upgrade_restart_manual": "Please restart the program manually.",
}

def t(key, **kwargs):
    return LANG[key].format(**kwargs)
